#!/usr/bin/env python
"""
calibrate_local_critic.py

Fit simple linear calibration curves that align the offline/local critic's
predictions with reference critic scores (e.g., OpenAI). This produces a JSON
file consumed by consolidate_stage3.py / OfflineCritic to rescale scores.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import argparse
import json
from typing import Dict, List

import numpy as np

from config.settings import load_settings
from rapbot.reward_model import LocalCritic as RewardLocalCritic, LocalCriticConfig, SCORE_KEYS


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Calibrate local critic predictions to reference scores.")
    parser.add_argument(
        "--scored_dataset",
        type=str,
        default=None,
        help="Combined dataset generated by consolidate_stage3 (JSONL).",
    )
    parser.add_argument(
        "--local_critic_head",
        type=str,
        default=None,
        help="Path to reward_head.pt (required).",
    )
    parser.add_argument(
        "--siamese_model_dir",
        type=str,
        default=None,
        help="Directory containing the Siamese encoder (default from config).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Destination JSON file for calibration params (default: models/local_critic/calibration.json).",
    )
    parser.add_argument("--limit", type=int, default=None, help="Optional cap on records to process.")
    parser.add_argument("--config", type=str, default=None, help="Optional config file for defaults.")
    return parser.parse_args()


def read_scored_records(path: Path, limit: int | None) -> List[Dict]:
    records: List[Dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue
            records.append(record)
            if limit and len(records) >= limit:
                break
    return records


def extract_text(record: Dict) -> str | None:
    text = record.get("verse_text")
    if text:
        return text
    bars = record.get("bars")
    if isinstance(bars, list):
        lines = [bar.get("text", "") for bar in bars if isinstance(bar, dict)]
        if lines:
            lines.append("<END_SONG>")
            return "\n".join(lines)
    return None


def compute_calibration(pred: List[float], target: List[float]) -> Dict[str, float]:
    if len(pred) < 2:
        return {"slope": 1.0, "intercept": 0.0, "pearson_r": 0.0, "rmse": 0.0, "count": len(pred)}
    x = np.array(pred, dtype=np.float32)
    y = np.array(target, dtype=np.float32)
    slope, intercept = np.polyfit(x, y, 1)
    corr = float(np.corrcoef(x, y)[0, 1])
    adjusted = slope * x + intercept
    rmse = float(np.sqrt(((adjusted - y) ** 2).mean()))
    return {
        "slope": float(slope),
        "intercept": float(intercept),
        "pearson_r": corr,
        "rmse": rmse,
        "count": int(x.size),
    }


def main():
    args = parse_args()
    settings = load_settings(args.config)
    scored_path = Path(args.scored_dataset or settings.scored_dataset_path)
    if not scored_path.exists():
        raise FileNotFoundError(f"Scored dataset not found: {scored_path}")

    head_path = Path(args.local_critic_head or (settings.local_critic_dir / "reward_head.pt"))
    siamese_dir = Path(args.siamese_model_dir or settings.siamese_model_dir)
    output_path = Path(args.output or (settings.local_critic_dir / "calibration.json"))
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cfg = LocalCriticConfig(head_path=head_path, siamese_model_dir=siamese_dir)
    critic = RewardLocalCritic(cfg)

    records = read_scored_records(scored_path, args.limit)
    if not records:
        raise RuntimeError(f"No records found in {scored_path}")

    target_scores: Dict[str, List[float]] = {field: [] for field in SCORE_KEYS}
    predicted_scores: Dict[str, List[float]] = {field: [] for field in SCORE_KEYS}

    for record in records:
        critic_entry = record.get("critic") or {}
        verse_text = extract_text(record)
        if not verse_text:
            continue
        predictions = critic.score(verse_text)
        for field in SCORE_KEYS:
            target_value = critic_entry.get(field)
            pred_value = predictions.get(field)
            if target_value is None or pred_value is None:
                continue
            target_scores[field].append(float(target_value))
            predicted_scores[field].append(float(pred_value))

    calibration = {}
    for field in SCORE_KEYS:
        preds = predicted_scores[field]
        targets = target_scores[field]
        calib = compute_calibration(preds, targets)
        calibration[field] = calib
        print(
            f"[CALIBRATE] {field}: slope={calib['slope']:.3f} intercept={calib['intercept']:.3f} "
            f"pearson_r={calib['pearson_r']:.3f} rmse={calib['rmse']:.3f} (n={calib['count']})"
        )

    output_path.write_text(json.dumps(calibration, indent=2), encoding="utf-8")
    print(f"[DONE] Calibration saved to {output_path}")


if __name__ == "__main__":
    main()
